import os
from mistralai.client import Mistral
import logging

logger = logging.getLogger(__name__)

def generate_script(article_text: str, duration_seconds: int, social_footer: str = ""):
    """
    Generates a video script from article text using Mistral AI.
    Style: Summary + Opinionated Presenter.
    """
    api_key = os.getenv("MISTRAL_API_KEY")
    if not api_key:
        return {"status": "error", "message": "MISTRAL_API_KEY not found in environment"}

    client = Mistral(api_key=api_key)
    model = "mistral-large-latest" # Mistral Large is very capable

    # Calculate target word count (average speaking rate is 130-150 WPM)
    target_words = int((duration_seconds / 60) * 140)
    
    system_prompt = f"""
    You are an expert video script writer and charismatic storyteller for platforms like TikTok, Reels, and YouTube.
    Your task is to transform the provided article into a high-energy, viral-style video script in English.
    
    CRITICAL STRUCTURE:
    1. THE HOOK (0-5s): Start with a powerful, "scroll-stopping" hook. Use a surprising fact, a controversial question, or a bold claim immediately.
    2. THE STORY: Summarize the core of the article with opinionated, charismatic energy.
    3. THE WRAP-UP: End with a proper conclusion that ties the story together and leaves a lasting impression.
    
    Style Guidelines:
    1. Human Rhythm: Use conversational fillers (e.g., "Wait," "So," "Actually," "Believe it or not") and varying sentence lengths.
    2. Emotions & Actions: Include emotional cues and physical actions in brackets [ ] to guide the speaker.
       Example: "[Excitedly] You won't believe this! [Pause, leans in] I just found out..."
    3. Opinionated: Express a clear personality. Don't just read the news; react to it.
    4. Conversational: Use contractions (don't, it's) and direct address to the viewer ("You need to hear this").
    5. Target Length: approximately {target_words} words for a {duration_seconds} second video. 
       NOTE: If this is a 30s short, you may extend the script up to 60s if the story needs a better start or end.
    
    Output ONLY the script text with [Action/Emotion] markers.
    """

    try:
        response = client.chat.complete(
            model=model,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": f"Article Content:\n{article_text}"}
            ],
            temperature=0.7,
            max_tokens=target_words * 2 # Allow some buffer
        )

        script_text = response.choices[0].message.content.strip()
        
        # Generate innovative YouTube Metadata
        meta_prompt = f"""
        Based on this script, generate:
        1. An INNOVATIVE and CLICK-WORTHY YouTube Title (Max 100 chars). 
           CRITICAL: Identify any COMPANY NAMES mentioned in the script and add them as hashtags.
           - Use between 3 and 6 hashtags in total.
           - Ensure hashtags are relevant to the companies or core topic.
        2. An INFORMATIVE YouTube Description (approx 300 words).
           CRITICAL RULES for Description:
           - DO NOT include "Generated by Articlo AI" or any branding.
           - DO NOT use markdown characters like asterisks (*) or bold markers.
           - BEFORE the final hashtags, include the following social links:
{social_footer if social_footer else "             [Follow us on Instagram: https://instagram.com/your_profile]\n             [Join our Telegram for updates: https://t.me/your_channel]"}
           - End with at least 10 relevant viral hashtags.
        
        Script: {script_text[:1000]}
        
        Format as JSON: {{"title": "...", "description": "..."}}
        """
        
        meta_resp = client.chat.complete(
            model=model,
            messages=[{"role": "user", "content": meta_prompt}],
            response_format={"type": "json_object"}
        )
        
        import json
        yt_meta = json.loads(meta_resp.choices[0].message.content)
        
        return {
            "status": "success",
            "script": script_text,
            "youtube_meta": yt_meta,
            "word_count": len(script_text.split()),
            "target_duration": duration_seconds,
            "model": model
        }

    except Exception as e:
        logger.error(f"Mistral Error: {e}")
        return {"status": "error", "message": f"Mistral API Error: {str(e)}"}

def generate_linkedin_description(script_text: str, theme: str = "professional", social_footer: str = ""):
    """
    Generates a LinkedIn-specific description based on a theme/prompt.
    """
    api_key = os.getenv("MISTRAL_API_KEY")
    if not api_key:
        return {"status": "error", "message": "MISTRAL_API_KEY not found"}

    client = Mistral(api_key=api_key)
    model = "mistral-large-latest"

    prompt = f"""
    You are a professional LinkedIn content creator.
    Generate a LinkedIn post description for a video with the following script.
    
    THEME/STYLE: {theme}
    
    CRITICAL RULES:
    1. Hook: Start with a strong opening line suitable for LinkedIn's professional audience.
    2. Body: Expand on the topic in the style requested ({theme}). 
       - If it's "story", make it a narrative about learning or discovery.
       - If it's "conversation", make it an engaging question-driven post.
    3. Emojis: Include a good amount of relevant emojis throughout the post to make it visually engaging and professional (e.g. 🚀, ✨, 📈, 💡).
    4. Formatting: Use bullet points or short paragraphs. DO NOT use markdown like **bold**.
    5. Hashtags: Include 5-10 highly relevant and trending LinkedIn hashtags at the end.
    6. Length: approx 150-300 words.
    
    Video Script:
    {script_text[:2000]}
    
    Output ONLY the post text.
    """

    try:
        response = client.chat.complete(
            model=model,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.7
        )
        description = response.choices[0].message.content.strip()
        
        # Manually append social footer if provided, above hashtags
        if social_footer:
            # Try to find hashtags at the end
            import re
            parts = re.split(r'(#\w+)', description, 1)
            if len(parts) > 1:
                description = parts[0].strip() + "\n\n" + social_footer + "\n\n" + "".join(parts[1:]).strip()
            else:
                description = description + "\n\n" + social_footer
                
        return {"status": "success", "description": description}
    except Exception as e:
        logger.error(f"Mistral LinkedIn Error: {e}")
        return {"status": "error", "message": str(e)}
